const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');
const stream = require('stream');

/**
 * Helper to convert stream to buffer
 */
const streamToBuffer = async (readableStream) => {
  return new Promise((resolve, reject) => {
    const chunks = [];
    readableStream.on('data', chunk => chunks.push(chunk));
    readableStream.on('error', reject);
    readableStream.on('end', () => resolve(Buffer.concat(chunks)));
  });
};

/**
 * Generate a PDF for Documentation
 */
async function generatePDF(docData, website) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true });
      const pass = new stream.PassThrough();
      
      doc.pipe(pass);

      // Cover Page
      doc.fontSize(28).font('Helvetica-Bold').text('AI Generated Documentation', { align: 'center' });
      doc.moveDown();
      doc.fontSize(20).font('Helvetica').text(website.name, { align: 'center', color: '#4f46e5' });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica').text(website.url, { align: 'center', color: '#64748b' });
      doc.moveDown(5);
      doc.fontSize(10).font('Helvetica').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.addPage();

      // Helper for sections
      const addSection = (title, content) => {
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1e293b').text(title);
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica').fillColor('#334155').text(content, { align: 'justify' });
        doc.moveDown(1.5);
      };

      const addList = (title, items) => {
        if (!items || items.length === 0) return;
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1e293b').text(title);
        doc.moveDown(0.5);
        items.forEach(item => {
          doc.fontSize(11).font('Helvetica').fillColor('#334155').text(`• ${item}`, { indent: 20 });
        });
        doc.moveDown(1.5);
      };

      // Content
      if (docData.executiveSummary) addSection('Executive Summary', docData.executiveSummary);
      if (docData.websiteOverview) addSection('Website Overview', docData.websiteOverview);
      
      addList('Main Topics', docData.mainTopics);
      addList('Key Services', docData.keyServices);
      addList('Technologies', docData.technologies);
      
      if (docData.importantPages && docData.importantPages.length > 0) {
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1e293b').text('Important Pages');
        doc.moveDown(0.5);
        docData.importantPages.forEach(page => {
          doc.fontSize(12).font('Helvetica-Bold').fillColor('#334155').text(page.title);
          doc.fontSize(10).font('Helvetica').fillColor('#64748b').text(page.url);
          doc.fontSize(11).font('Helvetica').fillColor('#334155').text(page.description, { indent: 10 });
          doc.moveDown(0.5);
        });
        doc.moveDown();
      }

      if (docData.faq && docData.faq.length > 0) {
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1e293b').text('Frequently Asked Questions');
        doc.moveDown(0.5);
        docData.faq.forEach(q => {
          doc.fontSize(12).font('Helvetica-Bold').fillColor('#334155').text(`Q: ${q.question}`);
          doc.fontSize(11).font('Helvetica').fillColor('#334155').text(`A: ${q.answer}`, { indent: 15 });
          doc.moveDown(0.5);
        });
        doc.moveDown();
      }

      addList('AI Generated Insights', docData.aiInsights);
      addList('Contact Information', docData.contactInfo);
      
      // Footer & Page Numbers
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).font('Helvetica').fillColor('#94a3b8').text(
          `Page ${i + 1} of ${range.count} - Generated by WebMind AI`,
          50,
          doc.page.height - 50,
          { align: 'center' }
        );
      }

      doc.end();

      const buffer = await streamToBuffer(pass);
      resolve(buffer);
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate DOCX for Documentation
 */
async function generateDOCX(docData, website) {
  const children = [];

  // Title
  children.push(new Paragraph({ text: "AI Generated Documentation", heading: HeadingLevel.HEADING_1 }));
  children.push(new Paragraph({ text: website.name, heading: HeadingLevel.HEADING_2 }));
  children.push(new Paragraph({ text: `URL: ${website.url}` }));
  children.push(new Paragraph({ text: `Generated on: ${new Date().toLocaleDateString()}` }));
  children.push(new Paragraph({ text: "" })); // spacer

  const addTextSection = (title, text) => {
    if (!text) return;
    children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text }));
    children.push(new Paragraph({ text: "" }));
  };

  const addListSection = (title, items) => {
    if (!items || items.length === 0) return;
    children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_3 }));
    items.forEach(item => {
      children.push(new Paragraph({ text: item, bullet: { level: 0 } }));
    });
    children.push(new Paragraph({ text: "" }));
  };

  addTextSection('Executive Summary', docData.executiveSummary);
  addTextSection('Website Overview', docData.websiteOverview);
  
  addListSection('Main Topics', docData.mainTopics);
  addListSection('Key Services', docData.keyServices);
  addListSection('Technologies', docData.technologies);

  if (docData.importantPages && docData.importantPages.length > 0) {
    children.push(new Paragraph({ text: 'Important Pages', heading: HeadingLevel.HEADING_3 }));
    docData.importantPages.forEach(p => {
      children.push(new Paragraph({ children: [new TextRun({ text: p.title, bold: true })] }));
      children.push(new Paragraph({ text: p.url }));
      children.push(new Paragraph({ text: p.description }));
      children.push(new Paragraph({ text: "" }));
    });
  }

  if (docData.faq && docData.faq.length > 0) {
    children.push(new Paragraph({ text: 'Frequently Asked Questions', heading: HeadingLevel.HEADING_3 }));
    docData.faq.forEach(q => {
      children.push(new Paragraph({ children: [new TextRun({ text: `Q: ${q.question}`, bold: true })] }));
      children.push(new Paragraph({ text: `A: ${q.answer}` }));
      children.push(new Paragraph({ text: "" }));
    });
  }

  addListSection('AI Generated Insights', docData.aiInsights);
  addListSection('Contact Information', docData.contactInfo);

  const doc = new Document({
    sections: [{ properties: {}, children }]
  });

  return await Packer.toBuffer(doc);
}

/**
 * Generate Markdown for Documentation
 */
function generateMarkdown(docData, website) {
  let md = `# AI Generated Documentation\n\n`;
  md += `## ${website.name}\n**URL:** ${website.url}\n**Generated on:** ${new Date().toLocaleDateString()}\n\n---\n\n`;

  if (docData.executiveSummary) md += `### Executive Summary\n${docData.executiveSummary}\n\n`;
  if (docData.websiteOverview) md += `### Website Overview\n${docData.websiteOverview}\n\n`;

  const addList = (title, items) => {
    if (items && items.length > 0) {
      md += `### ${title}\n`;
      items.forEach(item => md += `- ${item}\n`);
      md += '\n';
    }
  };

  addList('Main Topics', docData.mainTopics);
  addList('Key Services', docData.keyServices);
  addList('Technologies', docData.technologies);

  if (docData.importantPages && docData.importantPages.length > 0) {
    md += `### Important Pages\n`;
    docData.importantPages.forEach(p => {
      md += `**${p.title}**\n[${p.url}](${p.url})\n${p.description}\n\n`;
    });
  }

  if (docData.faq && docData.faq.length > 0) {
    md += `### Frequently Asked Questions\n`;
    docData.faq.forEach(q => {
      md += `**Q: ${q.question}**\nA: ${q.answer}\n\n`;
    });
  }

  addList('AI Generated Insights', docData.aiInsights);
  addList('Contact Information', docData.contactInfo);

  return Buffer.from(md, 'utf8');
}

/**
 * Generate TXT for Documentation
 */
function generateTXT(docData, website) {
  let txt = `=================================================\n`;
  txt += `AI GENERATED DOCUMENTATION\n`;
  txt += `=================================================\n\n`;
  txt += `Website: ${website.name}\nURL: ${website.url}\nGenerated on: ${new Date().toLocaleDateString()}\n\n`;

  if (docData.executiveSummary) txt += `EXECUTIVE SUMMARY\n${docData.executiveSummary}\n\n`;
  if (docData.websiteOverview) txt += `WEBSITE OVERVIEW\n${docData.websiteOverview}\n\n`;

  const addList = (title, items) => {
    if (items && items.length > 0) {
      txt += `${title.toUpperCase()}\n`;
      items.forEach(item => txt += `- ${item}\n`);
      txt += '\n';
    }
  };

  addList('Main Topics', docData.mainTopics);
  addList('Key Services', docData.keyServices);
  addList('Technologies', docData.technologies);

  if (docData.importantPages && docData.importantPages.length > 0) {
    txt += `IMPORTANT PAGES\n`;
    docData.importantPages.forEach(p => {
      txt += `${p.title}\nURL: ${p.url}\nDescription: ${p.description}\n\n`;
    });
  }

  if (docData.faq && docData.faq.length > 0) {
    txt += `FREQUENTLY ASKED QUESTIONS\n`;
    docData.faq.forEach(q => {
      txt += `Q: ${q.question}\nA: ${q.answer}\n\n`;
    });
  }

  addList('AI Generated Insights', docData.aiInsights);
  addList('Contact Information', docData.contactInfo);

  return Buffer.from(txt, 'utf8');
}


// CHAT EXPORT
async function generateChatPDF(messages, website) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true });
      const pass = new stream.PassThrough();
      doc.pipe(pass);

      doc.fontSize(20).font('Helvetica-Bold').text('AI Conversation Export', { align: 'center' });
      doc.moveDown();
      doc.fontSize(14).font('Helvetica').text(`Website: ${website.name}`, { align: 'center', color: '#4f46e5' });
      doc.fontSize(10).font('Helvetica').text(`Exported on: ${new Date().toLocaleDateString()}`, { align: 'center', color: '#64748b' });
      doc.moveDown(2);

      messages.forEach(m => {
        const isAI = m.sender === 'ai';
        doc.fontSize(10).font('Helvetica-Bold').fillColor(isAI ? '#4f46e5' : '#1e293b').text(isAI ? 'AI Assistant:' : 'User:');
        doc.fontSize(11).font('Helvetica').fillColor('#334155').text(m.text || '');
        doc.moveDown();
      });

      doc.end();
      resolve(await streamToBuffer(pass));
    } catch(err) { reject(err); }
  });
}

function generateChatTXT(messages, website) {
  let txt = `=================================================\n`;
  txt += `AI CONVERSATION EXPORT\n`;
  txt += `=================================================\n\n`;
  txt += `Website: ${website.name}\nExported on: ${new Date().toLocaleDateString()}\n\n`;
  
  messages.forEach(m => {
    const role = m.sender === 'ai' ? 'AI Assistant' : 'User';
    txt += `[${role}]\n${m.text || ''}\n\n`;
  });
  
  return Buffer.from(txt, 'utf8');
}

// TRAINING REPORT EXPORT
async function generateReportPDF(website) {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, bufferPages: true });
      const pass = new stream.PassThrough();
      doc.pipe(pass);

      doc.fontSize(24).font('Helvetica-Bold').text('Website Training Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).font('Helvetica').text(website.name, { align: 'center', color: '#4f46e5' });
      doc.fontSize(12).font('Helvetica').text(website.url, { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1e293b').text('Training Metrics');
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica').fillColor('#334155')
         .text(`Status: ${website.status.toUpperCase()}`)
         .text(`Training Date: ${new Date(website.createdAt).toLocaleString()}`)
         .text(`Pages Crawled: ${website.pagesProcessed}`)
         .text(`Chunks Generated: ${website.totalChunks}`)
         .text(`Vector Database: ChromaDB`)
         .text(`Embedding Model: All-MiniLM-L6-v2`);
      doc.moveDown();
      
      if(website.summary && website.summary.executiveSummary) {
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1e293b').text('AI Generated Summary');
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica').fillColor('#334155').text(website.summary.executiveSummary, { align: 'justify' });
      }

      doc.end();
      resolve(await streamToBuffer(pass));
    } catch(err) { reject(err); }
  });
}


module.exports = {
  generatePDF,
  generateDOCX,
  generateMarkdown,
  generateTXT,
  generateChatPDF,
  generateChatTXT,
  generateReportPDF
};
