import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';

const faqs = [
  { q: "What is WebMind AI?", a: "WebMind AI is a platform that allows you to transform any public website into an interactive AI chatbot using Retrieval-Augmented Generation (RAG)." },
  { q: "How does RAG work?", a: "RAG searches and retrieves relevant page chunks matching your query, injecting them as context into the LLM to get factual, grounded answers based on your data." },
  { q: "Can I train multiple websites?", a: "Yes, depending on your plan, you can create separate bots for different websites and manage them all from a single dashboard." },
  { q: "How is my data stored?", a: "Your website data is chunked and embedded into high-dimensional vectors, stored securely in our isolated vector database (ChromaDB)." },
  { q: "Does it support private websites?", a: "Currently, our crawler only accesses publicly available URLs. Support for authenticated pages via OAuth or custom headers is on our roadmap." },
  { q: "Which AI models are supported?", a: "We primarily use Gemini for fast, accurate embeddings, and Groq/Llama for lightning-fast text generation, but the architecture supports plug-and-play LLMs." },
  { q: "Can I retrain a website?", a: "Yes. You can trigger a re-crawl at any time to update your vector database with the latest content from your website." },
  { q: "How are embeddings generated?", a: "Text content is split into semantic chunks (usually around 1000 tokens) and passed through an embedding model to generate numerical vectors." },
  { q: "How does semantic search work?", a: "Unlike keyword search, semantic search uses cosine similarity between your question's vector and your data's vectors to find meaning and intent." },
  { q: "Is authentication secure?", a: "Yes, we use industry-standard JWT authentication and bcrypt hashing to secure your account and API endpoints." },
  { q: "Can businesses use WebMind AI?", a: "Absolutely. Our platform is built for enterprise use-cases like internal knowledge bases, customer support bots, and developer documentation." },
  { q: "Does it support citations?", a: "Yes. Every answer generated by the AI includes specific links back to the exact URL and chunk it used to formulate the response." }
];

const FAQ = () => {
  const [openIdx, setOpenIdx] = useState(null);

  const toggle = (idx) => {
    setOpenIdx(openIdx === idx ? null : idx);
  };

  return (
    <section id="faq" className="py-24 max-w-4xl mx-auto px-6">
      <div className="text-center mb-16">
        <h2 className="text-3xl md:text-5xl font-bold mb-4">Frequently Asked <span className="gradient-text">Questions</span></h2>
        <p className="text-slate-400 text-lg">Everything you need to know about the product and billing.</p>
      </div>

      <div className="space-y-4">
        {faqs.map((faq, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.3, delay: idx * 0.05 }}
            className={`border rounded-2xl overflow-hidden transition-all duration-300 ${openIdx === idx ? 'bg-slate-800/60 border-indigo-500/50' : 'bg-slate-900/40 border-slate-700/50 hover:bg-slate-800/40'}`}
          >
            <button 
              onClick={() => toggle(idx)}
              className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
            >
              <span className="font-medium text-slate-200">{faq.q}</span>
              <ChevronDown className={`w-5 h-5 text-slate-400 transition-transform duration-300 ${openIdx === idx ? 'rotate-180 text-indigo-400' : ''}`} />
            </button>
            
            <AnimatePresence>
              {openIdx === idx && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                >
                  <div className="px-6 pb-6 text-slate-400 text-sm leading-relaxed border-t border-slate-700/30 pt-4">
                    {faq.a}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default FAQ;
